### ISSUE TITLE
数据集划分

### ISSUE THREAD

**Issue by nachifur** [nachifur/RDDM#14]
> 你好，请问在low-level vision中验证集和测试集是一个东西吗（表示疑惑）？

我注意到LOL数据集通常是这么做的：https://github.com/wyf0912/LLFlow/issues/51

想问下您ISTD 和 RainDrop数据集也是这么处理的吗？

_Originally posted by @flashszn in https://github.com/nachifur/RDDM/issues/2#issuecomment-2017596542_

**Comment by nachifur** [comment]
@flashszn 

对于ISTD，我们根据[DMTN中的代码](https://github.com/nachifur/DMTN/blob/main/script/generate_flist_istd.py)进行数据集划分：训练集、验证集、测试集，RDDM中没有使用验证集，仅使用了其中的训练集和测试集。

对于LOL、RainDrop、GoPro、SID-RGB，使用原始数据集的训练集和测试集（这些数据集没有提供验证集）。

对于celecba的数据集划分细节，可见：https://github.com/nachifur/RDDM/issues/8#issuecomment-1978889073

**Comment by flashszn** [comment]
> @flashszn
> 
> 对于ISTD、LOL、RainDrop、GoPro、SID-RGB，使用原始数据集的训练集和测试集。
> 
> 对于celecba的数据集划分细节，可见：[https://github.com/nachifur/RDDM/issues/8#issuecomment-1978889073。](https://github.com/nachifur/RDDM/issues/8#issuecomment-1978889073%E3%80%82)
> 
> 如果您需要在训练过程中评估模型性能（使用验证集），例如在ISTD上，可以参见[DMTN中代码](https://github.com/nachifur/DMTN/blob/main/script/generate_flist_istd.py)对训练集重新拆分成训练集和验证集。值得注意的是，RDDM仅是凭经验设置训练迭代次数，并没有`在验证集上不断调参优化`这一环节。

非常感谢作者的回复。
