### ISSUE TITLE
.flist无法识别

### ISSUE THREAD

**Issue by lwtgithublwt** [nachifur/RDDM#15]
您好，请问xxx/dataset/ISTD_Dataset_arg/data_val/ISTD_shadow_free_train.flist具体的格式是什么，为什么无法识别，报了以下错误：
PIL.UnidentifiedImageError: cannot identify image file '/mnt/disk1/4D3694572BC13DA1/lwt/RDDM-main/data/GTtrain.flist
改为图片地址后可以识别，但会出现新的错误AttributeError: 'int' object has no attribute 'size'，感谢您的答复。

**Comment by nachifur** [comment]
https://github.com/nachifur/RDDM/issues/2#issuecomment-1994604786

每一行是图片的绝对路径。

**Comment by JayYik** [comment]
可能是你的numpy版本过高导致[L160](https://github.com/nachifur/RDDM/blob/11d06d5f389e3953fdedcf33fffbb81ff4d1583a/datasets/base.py#L160) 里面的np.str报错，我尝试更改成了str

**Comment by lwtgithublwt** [comment]
@JayYik 非常感谢

**Comment by Curry704** [comment]
@lwtgithublwt 请问是怎么解决的呢，我现在生成不了.flist文件
