### ISSUE TITLE
GOPRO的训练数据选择的问题

### ISSUE THREAD

**Issue by ZhengHSI** [nachifur/RDDM#16]
您好，请问您在使用GOPRO数据集训练模型时，使用的是gamma矫正后的数据集还是未矫正的数据集。

**Comment by nachifur** [comment]
GOPRO数据集下载：

https://github.com/swz30/MPRNet/tree/main/Deblurring

**Comment by ZhengHSI** [comment]
非常感谢作者的回复，但是我保存了您给的链接中关于gopro的数据集，我发现链接中gopro训练集中target数量只有有2057张，input只有1855张，这和原始gopro数据集 2,103 张训练图像好像不太符合，请问是做了什么处理么

**Comment by ZhengHSI** [comment]
<img width="995" alt="image" src="https://github.com/nachifur/RDDM/assets/75197202/f9666a42-1d5d-4697-94c0-624819a6a94d">
<img width="852" alt="image" src="https://github.com/nachifur/RDDM/assets/75197202/acf2de4b-6cc5-42b8-8f11-1d97c0aa3bfc">
