### ISSUE TITLE
尊敬的作者您好！想请问一下关于训练的问题

### ISSUE THREAD

**Issue by Tiehr2000** [nachifur/RDDM#17]
请问在train.py训练代码中，ResidualDiffusion类的timesteps参数默认为1000，这对图像恢复任务的训练有什么样的影响呢？
论文附录中，我有看到各个任务的Sampling steps设置，请问对应的timesteps应该怎么设置呀，非常感谢！

**Comment by nachifur** [comment]
timesteps根据之前DDPM、DDIM默认设置为1000。

Sampling steps采样数据在测试阶段可以自己设置，和训练没关系。
