### ISSUE TITLE
Questions about #params and flops

### ISSUE THREAD

**Issue by lazywu170101** [nachifur/RDDM#18]
Dear Author, Thank you for your outstanding paper, the methodology proposed in the article is very innovative and worth learning. I have some questions about the article: 
1. What is the parameter size (#params) of the method proposed in the article? 
2. From efficient and runtime considerations , how does it compare with other methods? 
3. what is the value of flops?
Thanks again for your contribution, and I hope to hear from you!

**Comment by nachifur** [comment]
See Table 11 in Appendix.

**Comment by lazywu170101** [comment]
Thank you for your reply! It was an oversight on my part and I apologize for that.
