### ISSUE TITLE
cannot find the part 

### ISSUE THREAD

**Issue by billie2jean** [nachifur/RDDM#19]
Hi! Thanks for your wonderful work!
I have learned your paper and code, but I dont find the part of Simultaneous Removal Of Residuals and Noise. I would appreciate it if u can help me.

**Comment by nachifur** [comment]
uncomment this line: https://github.com/nachifur/RDDM/blob/7cbb21139f33e7fe453aa1e8105a2371fa8eb5ee/src/residual_denoising_diffusion_pytorch.py#L1119

**Comment by billie2jean** [comment]
Thx, I think it's my carelessness :)
