### ISSUE TITLE
图像生成任务的默认设置问题

### ISSUE THREAD

**Issue by Johnson-yue** [nachifur/RDDM#20]
作者你好，非常感谢你放出来CVPR2024的工作源码，同时也提供了中文的论文方便我们理解。我在使用celebA 数据集 64x64的图像进行图像生成任务的时候， 发现默认的设置有些疑问导致训练不成功。

在train.py 的文件中默认设置的object 是 pred_res_noise 然后用两个Unet来预测。 但是 test_res_or_noise 设置的为 ”noise“, 在训练的时候只使用了 一个Unet的预测结果，这个是为什么？？ 而且因为设置的的2个Unet，所以model_output = （0， xx），所以训练的时候，会报错 int 没有 size这个属性。

**Comment by nachifur** [comment]
1. test_res_or_noise = "res_noise"

2. `[self.alphas_cumsum[t]*self.num_timesteps, self.betas_cumsum[t]*self.num_timesteps]]` -> `[t,t]` (in [L852](https://github.com/nachifur/RDDM/blob/50d7dc3670a68dfe89c411a9445cc824b4fcd911/src/residual_denoising_diffusion_pytorch.py#L852) and [L1292](https://github.com/nachifur/RDDM/blob/50d7dc3670a68dfe89c411a9445cc824b4fcd911/src/residual_denoising_diffusion_pytorch.py#L1292))

**Comment by Johnson-yue** [comment]
> 可以尝试修改：
> 
> 1. test_res_or_noise = "res_noise" （测试阶段可以修改test_res_or_noise = "noise" or “res” ）
> 2. `[self.alphas_cumsum[t]*self.num_timesteps, self.betas_cumsum[t]*self.num_timesteps]]` -> `[t,t]` (in [L852](https://github.com/nachifur/RDDM/blob/50d7dc3670a68dfe89c411a9445cc824b4fcd911/src/residual_denoising_diffusion_pytorch.py#L852) and [L1292](https://github.com/nachifur/RDDM/blob/50d7dc3670a68dfe89c411a9445cc824b4fcd911/src/residual_denoising_diffusion_pytorch.py#L1292))

非常感谢，解决了我的疑问。
