### ISSUE TITLE
关于ReadMe中的取消注释同时预测noise和res的疑问

### ISSUE THREAD

**Issue by Johnson-yue** [nachifur/RDDM#21]
![image](https://github.com/nachifur/RDDM/assets/10268274/d167ddfb-5367-4f26-abb7-cb10a4a8040f)
在readme中这个部分，没有看懂。在原始代码中就有一个 ddim_sample函数[ddim_sample](https://github.com/nachifur/RDDM/blob/e5bdeee874d855c9f38c11536adcc9efee329810/src/residual_denoising_diffusion_pytorch.py#L966) 但是 如果按照readme取消注释，那么就会有两个 ddim_sampler 函数，在做图像生成任务的时候应该使用哪一个？ 

我也对比了 原始的ddim_sample和 注释下的ddim_sample，  原始的ddim_sample函数是有2个 ”sampling loop time step“ 不知道是什么意思，希望能得到解答，谢谢， 我做的是text2image的图像生成任务使用，应该使用代码中的哪个ddim_sample？

**Comment by nachifur** [comment]
当前的设置是训练两个unet（一个用于估计残差，一个用于估计噪声），用于探索部分路径无关的生成过程。

正常使用需要：
uncomment [L726](https://github.com/nachifur/RDDM/blob/7cbb21139f33e7fe453aa1e8105a2371fa8eb5ee/src/residual_denoising_diffusion_pytorch.py#L1119) for simultaneous removal of residuals and noise.

**Comment by Johnson-yue** [comment]
明白了，如何是正常使用的话，其实是可以同时去除残差和噪声的， 也就是被注释的ddim_sample，谢谢
