### ISSUE TITLE
关于条件生成问题

### ISSUE THREAD

**Issue by Johnson-yue** [nachifur/RDDM#22]
我在测试代码的时候发现，这个代码只提供了无条件生成的例子，不知道你们做过条件生成的实验嘛？？ 我现在修改成支持cfg的条件生成模式， 对于预测的噪声来说， noise = uncond_noise + cfg_scale * （cond_noise - uncond_noise） ， 然后对于预测残差的部分，我按照噪声的方法 写成 res = uncond_res + cfg_scale * (cond_res - uncond_res) , 不知道是否正确？

**Comment by nachifur** [comment]
暂时没有进行有条件生成，可以自行推导和修改。
