### ISSUE TITLE
关于ddim_sample中的type == "special_eta_0"和type == "special_eta_1"

### ISSUE THREAD

**Issue by wangtuo111** [nachifur/RDDM#23]
你好，我想问一下当我同时去残差和去噪时，这两种 "special_eta_0"和"special_eta_1"反向过程如何理解
elif type == "special_eta_0":
    img = img - alpha*pred_res - \
        (betas_cumsum-betas_cumsum_next)*pred_noise
elif type == "special_eta_1":
    img = img - alpha*pred_res - betas2/betas_cumsum*pred_noise + \
        betas*betas2_cumsum_next.sqrt()/betas_cumsum*noise

**Comment by nachifur** [comment]
早期的无用代码（已清除），不用理会
