### ISSUE TITLE
生成图像质量问题

### ISSUE THREAD

**Issue by OPMZZZ** [nachifur/RDDM#28]
作者你好，我目前在学习你的论文并尝试复现你的模型。我在尝试进行图像恢复任务时，测试生成的最终图像会出现类似噪声的全局噪点，这是什么原因呢？我已经根据你工作的附录部分修改了超参数，是出现了什么遗漏吗？

生成图像:
![image](https://github.com/user-attachments/assets/b480bd04-7630-4924-ab40-f18fd0e4b225)

原始图像：
![image](https://github.com/user-attachments/assets/088c9dce-92ed-460c-8dd0-ba2ba07c4965)

**Comment by nachifur** [comment]
https://github.com/nachifur/RDDM/issues/2#issuecomment-2175338649
