### ISSUE TITLE
如何预训练扩散模型

### ISSUE THREAD

**Issue by Sci-Epiphany** [nachifur/RDDM#29]
请问大佬是如何在GoPro数据集上进行Unet模型的预训练的呢？因为GoPro图片数量比较少，之前训练的improved diffusion效果很差。
还有一个问题GoPro的图像大小是裁剪为256x256的吗，如果是裁剪的最终是怎么将结果拼接到一块的呢？

**Comment by nachifur** [comment]
没有预训练，可以直接训练。

**Comment by Sci-Epiphany** [comment]
您的意思是不用在GoPro数据集上进行扩散模型的调优对吧，但是我如果直接用imagenet训练好的diffusion model的pt文件时，效果很差，想请教您是如何解决该问题的，非常感谢您



---原始邮件---
发件人: "Jiawei ***@***.***&gt;
发送时间: 2024年9月6日(周五) 中午11:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [nachifur/RDDM] 如何预训练扩散模型 (Issue #29)




 
没有预训练，可以直接训练。

**Comment by nachifur** [comment]
不需要预训练，直接在GoPro数据集训练就行
