### ISSUE TITLE
有与Palette，I2SB这些方法的直接比较吗

### ISSUE THREAD

**Issue by YuChen-Liang** [nachifur/RDDM#3]

**Comment by nachifur** [comment]
Palette应该是基于DDPM的，完全从噪声逆向到清晰图像（不必要，因为退化图像已知，这也是下面这些方法的动机）。

RDDM，InDI，I2SB和 IR-SDE都是三项的混合（见section3.1），本质是一致的（如果不考虑系数时间表）。

**Comment by YuChen-Liang** [comment]
从12式来看，预测I_0, I_res, epsilon似乎是等价，三种方式的差异仅在于参数化形式和权重的不同吗？

**Comment by nachifur** [comment]
loss也可能有些差异
