### ISSUE TITLE
cumsum_prev 有误？

### ISSUE THREAD

**Issue by czzbb** [nachifur/RDDM#30]
您好，请问 https://github.com/nachifur/RDDM/blob/c8a4a846d1f5b22e2c533c601f526ad15980272f/src/residual_denoising_diffusion_pytorch.py#L680 与https://github.com/nachifur/RDDM/blob/c8a4a846d1f5b22e2c533c601f526ad15980272f/src/residual_denoising_diffusion_pytorch.py#L681 行中，pad的value为什么是1？我的理解是0。

**Comment by nachifur** [comment]
这个填0或1应该影响不大，因为这个“数值”也没有其他含义，仅是对齐维度

**Comment by czzbb** [comment]
好的，感谢解答

**Comment by czzbb** [comment]
好的，感谢解答~
