### ISSUE TITLE
关于去雨的训练

### ISSUE THREAD

**Issue by AochenA** [nachifur/RDDM#31]
![图片1](https://github.com/user-attachments/assets/1d658019-158f-4dd2-bc97-f67365da6c85)
新更新的代码要训练那么长时间吗？
用的3090 24g显存的卡

**Comment by nachifur** [comment]
修改一下：train_num_steps = 120000

**Comment by AochenA** [comment]
修改后还是需要1200多个小时

**Comment by bnufw** [comment]
是不是因为没用GPU的原因
