### ISSUE TITLE
咨询图像生成问题

### ISSUE THREAD

**Issue by jjjjjgggj** [nachifur/RDDM#32]
作者你好！我想咨询一下，关于该模型最简单的图像生成问题，在0_Partially_path-indenpent_generation中，想训练最基本的celeba生成，folder = 'xxx/CelebA/img_align_celeba'原代码是这个，我该如何修改呢？希望作者有时间能解答一下！十分感谢

**Comment by nachifur** [comment]
训练celeba：https://github.com/nachifur/RDDM/tree/main/experiments/6_Image_Generation_table2_decreased_alpha_increased_beta

运行`train.py`就行，会自动下载。
