### ISSUE TITLE
关于使用GPU的问题

### ISSUE THREAD

**Issue by bnufw** [nachifur/RDDM#36]
在做raindrop时，发现device用的是self.accelerator.device，但是运行的时候没有用到GPU，我简单改为'cuda'却会报错，不知道该如何使用GPU，还望指点一下，感谢

**Comment by nachifur** [comment]
https://github.com/nachifur/RDDM/blob/461957d0e9b22e4ada7daceb75ae7349202eea85/experiments/2_Image_Restoration_deraing_raindrop_noise1/train.py#L10

可能是你那边仅有一张显卡，改成0就行
