### ISSUE TITLE
模型输入的问题

### ISSUE THREAD

**Issue by xiangyundeyun** [nachifur/RDDM#37]
您好，我想请教您一个比较简单的问题，就是关于模型的输入，因为文章中定义了目标图像I0,退化图像Iin,还有残差Ires,那么在输入到扩散模型中的是以I0还是Iin呢，因为如果是做图像修复的话，那么最开始手上只有退化的图像，那么也不知道修复后的图像长什么样，那么也不知道之间的残差是多少，那么这样该怎么理解呢

**Comment by nachifur** [comment]
输入见公式14-15，I_t, t, I_in
