### ISSUE TITLE
测试

### ISSUE THREAD

**Issue by TonFard** [nachifur/RDDM#4]
![Uploading Snipaste_2023-11-10_10-07-41.png…]()
请问，我在使用你们的模型进行去噪训练，如何使用自己的图片进行测试呢

**Comment by TonFard** [comment]
original_ddim_ddpm = False
num_unet = 2
objective = 'pred_res_noise'
test_res_or_noise = "res_noise"
if original_ddim_ddpm:
    model = Unet(
        dim=64,
        dim_mults=(1, 2, 4, 8)
    )
    diffusion = GaussianDiffusion(
        model,
        image_size=image_size,
        timesteps=1000,           # number of steps
        sampling_timesteps=sampling_timesteps_original_ddim_ddpm,
        loss_type='l1',            # L1 or L2
    )
else:
    model = UnetRes(
        dim=64,
        dim_mults=(1, 2, 4, 8),
        num_unet=num_unet,
        condition=condition,
        input_condition=input_condition,
        objective=objective,
        test_res_or_noise=test_res_or_noise
    )
    diffusion = ResidualDiffusion(
        model,
        image_size=image_size,
        timesteps=1000,           # number of steps
        # number of sampling timesteps (using ddim for faster inference [see citation for ddim paper])
        sampling_timesteps=sampling_timesteps,
        objective=objective,
        loss_type='l2',            # L1 or L2
        condition=condition,
        sum_scale=sum_scale,
        input_condition=input_condition,
        input_condition_mask=input_condition_mask,
        test_res_or_noise=test_res_or_noise
    )


这是我的配置

**Comment by Z0Victor** [comment]
请问您是用多少张卡训练的

**Comment by nachifur** [comment]
感谢大家关注RDDM。去噪可以参考一下另一个issue，https://github.com/nachifur/RDDM/issues/2。

单卡3090就可以跑论文里绝大多数的实验。

抱歉，这几天事情比较多，过段时间会更新代码。

**Comment by TonFard** [comment]
8g显存的卡一个batchsize能跑起来

**Comment by Z0Victor** [comment]
> 8g显存的卡一个batchsize能跑起来

好的，感谢您

**Comment by CrazyBrick** [comment]
> 8g显存的卡一个batchsize能跑起来

@TonFard @nachifur 
不好意思，我刚接触这个，还是没有太看明白怎么改。请问如果我最开始只想在一些照片上获取“去噪”（去雨或者去阴影）的推理结果，这是可以直接做的吗（能接受未经训练表现差一点），应该执行哪个脚本做哪些修改呢？望回复，谢谢～
