### ISSUE TITLE
关于预训练权重

### ISSUE THREAD

**Issue by EricShenYuQi** [nachifur/RDDM#40]
请问提供的预训练权重是用于人脸生成的还是图像复原任务的？如果可以的话麻烦提供各个图像复原任务的预训练权重，谢谢

**Comment by nachifur** [comment]
提供的预训练权重是用于探索 partially path-independent generation process：[Two unets (deresidual+denoising) for partially path-independent generation process](https://rec.ustc.edu.cn/share/3d8d9200-4e7e-11ef-b0ee-250e7e41f368)
