### ISSUE TITLE
关于输出

### ISSUE THREAD

**Issue by wendeyy** [nachifur/RDDM#41]
作者你好，输出的结果是会放在results/test_timestep_10里面吗，我测试过后发现test_timestep_10文件夹里的图片与输入图片相比有变化是为什么。以及我想问一下训练大概要跑多少轮才会比较有效呢，我看使用代码中的默认参数我用单卡得跑两个星期

**Comment by brycekl** [comment]
楼主你好，能不能问问你的环境怎么装的呢，我用conda env create -f install.yaml报错
The following packages are not available from current channels:
  - urllib3==1.26.12=py37h06a4308_0
  - typing_extensions==4.3.0=py37h06a4308_0
  - tornado==6.2=py37h5eee18b_0
 - ......

**Comment by wendeyy** [comment]
@brycekl 你分开装试一下

**Comment by nachifur** [comment]
> 作者你好，输出的结果是会放在results/test_timestep_10里面吗，我测试过后发现test_timestep_10文件夹里的图片与输入图片相比有变化是为什么。以及我想问一下训练大概要跑多少轮才会比较有效呢，我看使用代码中的默认参数我用单卡得跑两个星期

1.变化可能是由于resize到256？
2.迭代次数设置按照table4

**Comment by larsvivi** [comment]
> 楼主你好，能不能问问你的环境怎么装的呢，我用conda env create -f install.yaml报错 The following packages are not available from current channels:
> 
> * urllib3==1.26.12=py37h06a4308_0
> * typing_extensions==4.3.0=py37h06a4308_0
> * tornado==6.2=py37h5eee18b_0
> * ......

你好，请问你问题解决了吗
