### ISSUE TITLE
图像补全任务的训练

### ISSUE THREAD

**Issue by Delta0406** [nachifur/RDDM#45]
请问如何将RDDM用于图像补全任务的训练呢？和去噪、去雨一样的流程吗？

**Comment by nachifur** [comment]
https://github.com/nachifur/RDDM/tree/main/experiments/4_Image_Inpainting_imgsize64_batch64_pred_res_noise_centermask_wo_mask_wo_input

**Comment by Delta0406** [comment]
> https://github.com/nachifur/RDDM/tree/main/experiments/4_Image_Inpainting_imgsize64_batch64_pred_res_noise_centermask_wo_mask_wo_input

谢谢您快速耐心的回复，这几天我看了一下代码，还有一些问题没有弄清楚，想要再请教一下您。目前这个实验4是以图像翻译任务为例来编写代码的，而我想要利用RDDM做图像补全，以Celeba-HQ为例，我应该如何更改以执行一个图像补全任务的训练呢？如下图所示，需要将图中input_condition和input_condition_mask置为true，img_to_img-translation置为false吗？folder中的六个文件列表又代表什么呢？
![image](https://github.com/user-attachments/assets/fe40020a-a2c8-4494-8944-244df518bb7f)
另外，注意到UnetRes网络中输入的时间步self.alphas_cumsum[t]*self.num_timesteps，想要请教一下您为什么要这样操作，而不是只输入退化图像和时间步呢？非常期待您的解答，万分感谢！
![760f56570b548aa5154d318c4feb11e](https://github.com/user-attachments/assets/7aa58368-8619-40e8-b630-56546b1602e5)

**Comment by nachifur** [comment]
你尝试实际运行一下train.py，是图像补全的->见dataset加载。

[    if inpaint:](https://github.com/nachifur/RDDM/blob/1891cdc49159fc10963db637e3e408c539e54b7d/experiments/4_Image_Inpainting_imgsize64_batch64_pred_res_noise_centermask_wo_mask_wo_input/datasets/get_dataset.py#L38)
