### ISSUE TITLE
pre_trained model mismatch unets 

### ISSUE THREAD

**Issue by BLACKICE456** [nachifur/RDDM#48]
I tried to load the pre-trained model for independent generation task, but the ckpt did not match the size of unet. May I ask if anyone know about this issue?
![353BCF07@E163C416 8DB85167](https://github.com/user-attachments/assets/1d68484b-0bf8-4911-bf77-aeeadb28bdcf)

**Comment by nachifur** [comment]
We only provide [the pre-trained models (two unets, deresidual+denoising)](https://rec.ustc.edu.cn/share/3d8d9200-4e7e-11ef-b0ee-250e7e41f368) for [partially path-independent generation process](https://github.com/nachifur/RDDM/tree/main/experiments/0_Partially_path-independent_generation). 

For `experiments/5_Image_translation_dog_to_cat_wo_input_imgsize64_batch64_pred_res_noise`, you need to train the model.
