### ISSUE TITLE
运行不起来

### ISSUE THREAD

**Issue by nil0330** [nachifur/RDDM#5]
你好我是第一次运行这个代码，想问如何替换自己的代码或是基于您代码中的示例运行查看效果
![image](https://github.com/nachifur/RDDM/assets/76889548/b2abf50c-e2d9-41df-a141-71e15370811c)
比如这个数据集如何替换，数据集应该满足什么要求

**Comment by nachifur** [comment]
生成任务：单图像数据集图像恢复：成对数据集（阴影去除需额外加mask作为输入）。参考https://github.com/nachifur/RDDM/issues/2发自我的荣耀手机-------- 原始邮件 --------发件人： nil0330 ***@***.***>日期： 2023年11月26日周日 下午3:49收件人： nachifur/RDDM ***@***.***>抄送： Subscribed ***@***.***>主    题： [nachifur/RDDM] 运行不起来 (Issue #5)
你好我是第一次运行这个代码，想问如何替换自己的代码或是基于您代码中的示例运行查看效果
image.png (view on web)
比如这个数据集如何替换，数据集应该满足什么要求
