### ISSUE TITLE
关于test的问题

### ISSUE THREAD

**Issue by jole878788** [nachifur/RDDM#50]
在做去雨的test的时候
我将$model-100.pt$放到了result路径中的$/home/steve/IJCNN_2025/RDDM/experiments/2_Image_Restoration_deraing_raindrop_noise1/results/model-100.pt$
但是根据生成出来的图像好像并没有看到其使用预训练模型来进行test，请问是哪里出了问题吗
而且也好奇一点，这个test的到底是处理raindrop还是ISTD数据集的这个目前还没有理解，请您解答一下
![image](https://github.com/user-attachments/assets/d849fc82-a7c6-4d70-80d6-54258d2ca11f)

**Comment by nachifur** [comment]
我们暂时没有提供去雨的预训练权重，你直接训一下就行。

预训练权重放在/results/sample
