### ISSUE TITLE
test输入数据

### ISSUE THREAD

**Issue by GrittingLeo** [nachifur/RDDM#51]
打扰了，请教一下作者。我在做去雨任务推理的时候，推理图片是没有gt的，所以输入len(folder) == 3。但是在运行时报错。
![1](https://github.com/user-attachments/assets/c1bc470d-2970-45db-b1e8-e1eaa66e4a44)

我检查了residual_denoising_diffusion_pytorch.py 的1212-1226行，这里的len(folder) == 3逻辑没问题呀。
![2](https://github.com/user-attachments/assets/871f5099-9c15-40af-bf70-21e5122b85a1)
有种解决办法就是强行把输入len(folder) 设置为4，把test_gt 重复设置为test_input的路径,不知道这样会不会影响推理结果。
万分感谢！

**Comment by nachifur** [comment]
https://github.com/nachifur/RDDM/tree/main/experiments/2_Image_Restoration_deraing_raindrop_noise1

图像恢复（去雨）使用这个代码
