### ISSUE TITLE
能否将该方法使用到机器人2D occ预测

### ISSUE THREAD

**Issue by daleigehhh** [nachifur/RDDM#53]
您好，我在做小车高动态场景导航，想通过结合occ预测与最优控制。机器人occ是通过将每一帧单线雷达结果建成occ地图(2值占用地图)，由于小车每个时间步的速度控制是可以获取的，所以后一帧后几帧的occ是可以用运动+前几帧的激光雷达扫描结果获取的(但是缺少部分前几帧没扫描到的地方的信息)，因此我只需要学一个残差即可很好的预测(恢复)后面帧的地图，感觉你的方法很适合，你觉得如何。

**Comment by nachifur** [comment]
可以尝试一下
