### ISSUE TITLE
如果我想应用该方法到语音去噪任务上，更推荐表4中哪一列参数？还是说需要自己调

### ISSUE THREAD

**Issue by KarsonYu** [nachifur/RDDM#55]
--来自没有调参经验的小白

**Comment by nachifur** [comment]
可以尝试一下图像恢复去雨的设置，或者只估计残差

**Comment by KarsonYu** [comment]
> 可以尝试一下图像恢复去雨的设置，或者只估计残差

按照这样理解的话，控制噪声的强度$`\bar{\beta}_T^2`$，也就是sum_scale是否应该设置小一点，如其他列中的0.01，不知道我理解的是否正确

**Comment by nachifur** [comment]
都可以尝试一下
