### ISSUE TITLE
Image Quality Issues for image translation tasks

### ISSUE THREAD

**Issue by sun11711** [nachifur/RDDM#56]
Hello, author, I would like to ask about the image translation task. I just replaced the data set to achieve a color restoration effect of the mural, but I feel that the details of the image are lost. Do you know what is the reason.

**Comment by sun11711** [comment]
![微信截图_20241224173120](https://github.com/user-attachments/assets/8e44843c-8069-4290-b0a6-79ec1c30cc02)

**Comment by nachifur** [comment]
For image translation, we have only preliminarily verified the feasibility, and given a demo code. This requires further experimental exploration. 

I think a cyclegan-like consistency loss function is needed for image translation, which could be a novel IDEA. If you'd like, we can work on it together.

**Comment by sun11711** [comment]
Ok, thanks for the reply. I noticed that there are many authors using diffusion models to implement unpaired image transformation tasks, including image restoration tasks such as rain removal and low light enhancement, but most of them do not have open source code. I want to use the above knowledge to achieve the task of color reproduction.
