### ISSUE TITLE
关于损失函数的一个错误

### ISSUE THREAD

**Issue by nil0330** [nachifur/RDDM#6]
我依照你的修改意见修改了代码
![image](https://github.com/nachifur/RDDM/assets/76889548/433756de-d6e3-4487-8f7c-0a9f5064ebd9)
但是代码报错
![image](https://github.com/nachifur/RDDM/assets/76889548/c0076288-8028-4885-8016-3d1a3d2bb399)
![image](https://github.com/nachifur/RDDM/assets/76889548/15a81bb2-17ed-4efd-bc30-815dd8e84b7a)
![image](https://github.com/nachifur/RDDM/assets/76889548/dff47a6f-7b9f-4e30-84a0-4997a385c943)
请问这是什么原因

**Comment by nil0330** [comment]
另外我发现我的modelout是一个tuple类型形式如下：
![image](https://github.com/nachifur/RDDM/assets/76889548/6a65030b-0b1b-493e-a7bb-36f250bdb92c)
第一个是int类型第二个为tensor的形状为[1,3,256,256]
请问你运行时也是这种情况吗

**Comment by TuTusong** [comment]
作者您好，我再尝试图像修复任务过程中想使用两个网络，同样遇到了这个问题，想问下这是什么原因呢？
![image](https://github.com/nachifur/RDDM/assets/126681538/3968bfb5-bcb5-4caf-a0e7-454cb2fc3bb6)
