### ISSUE TITLE
关于训练的一些疑问

### ISSUE THREAD

**Issue by flashszn** [nachifur/RDDM#7]
你好，我阅读了您的论文，并对此非常感兴趣，打算复现您的实验。
我有个疑问想请教一下：RDDM用于图像修复的任务时，使用的权重是DDIM的权重进行微调，还是直接从零开始训练？

**Comment by nachifur** [comment]
从零开始

**Comment by flashszn** [comment]
那实在是太酷了

**Comment by flashszn** [comment]
> 从零开始

那实在是太酷了

**Comment by flashszn** [comment]
你好，我是第一次做图像修复任务，我有一些疑惑：

1. 我注意到训练的时候进入网络的时候图像大小是256*256，但推理的时候却不是了。
2. 请问推理的时候对原始图像的处理流程是什么样的，是简单的center_crop？还是直接进入原图，但是神经网络的训练输入是256*256，这样不会导致其精度下降吗？

**Comment by flashszn** [comment]
> 你好，我是第一次做图像修复任务，我有一些疑惑：
> 
> 1. 我注意到训练的时候进入网络的时候图像大小是256*256，但推理的时候却不是了。
> 2. 请问推理的时候对原始图像的处理流程是什么样的，是简单的center_crop？还是直接进入原图，但是神经网络的训练输入是256*256，这样不会导致其精度下降吗？

更具体的，我正在复现关于ISTD数据集的部分，我对于您的数据预处理的代码有些费解，我的理解是：

1. 训练阶段：先将原始图片用黑色填充为一个方形，然后进行随机反转并resize到256*256（我并不是很理解，如有错误还请指正）。
2. 推理阶段：直接放入原图进行推理（也有可能我理解错了）

**Comment by nachifur** [comment]
> 你好，我是第一次做图像修复任务，我有一些疑惑：
> 
> 1. 我注意到训练的时候进入网络的时候图像大小是256*256，但推理的时候却不是了。
> 2. 请问推理的时候对原始图像的处理流程是什么样的，是简单的center_crop？还是直接进入原图，但是神经网络的训练输入是256*256，这样不会导致其精度下降吗？

训练和测试都是resize到256

**Comment by nachifur** [comment]
> > 你好，我是第一次做图像修复任务，我有一些疑惑：
> > 
> > 1. 我注意到训练的时候进入网络的时候图像大小是256*256，但推理的时候却不是了。
> > 2. 请问推理的时候对原始图像的处理流程是什么样的，是简单的center_crop？还是直接进入原图，但是神经网络的训练输入是256*256，这样不会导致其精度下降吗？
> 
> 更具体的，我正在复现关于ISTD数据集的部分，我对于您的数据预处理的代码有些费解，我的理解是：
> 
> 1. 训练阶段：先将原始图片用黑色填充为一个方形，然后进行随机反转并resize到256*256（我并不是很理解，如有错误还请指正）。
> 2. 推理阶段：直接放入原图进行推理（也有可能我理解错了）

image_size=256
crop_patch=False 

训练和测试都是resize到256，`func:pad_img`没有改变图像。

**Comment by flashszn** [comment]
> > > 你好，我是第一次做图像修复任务，我有一些疑惑：
> > > 
> > > 1. 我注意到训练的时候进入网络的时候图像大小是256*256，但推理的时候却不是了。
> > > 2. 请问推理的时候对原始图像的处理流程是什么样的，是简单的center_crop？还是直接进入原图，但是神经网络的训练输入是256*256，这样不会导致其精度下降吗？
> > 
> > 
> > 更具体的，我正在复现关于ISTD数据集的部分，我对于您的数据预处理的代码有些费解，我的理解是：
> > 
> > 1. 训练阶段：先将原始图片用黑色填充为一个方形，然后进行随机反转并resize到256*256（我并不是很理解，如有错误还请指正）。
> > 2. 推理阶段：直接放入原图进行推理（也有可能我理解错了）
> 
> image_size=256 crop_patch=False
> 
> 训练和测试都是resize到256，`func:pad_img`在这里事实上没有改变图像。

非常感谢！

**Comment by flashszn** [comment]
非常抱歉打扰您，我需要再确认下，您在修复任务上，包括：RainDrop数据集，LOL数据集、ISTD数据集和GoPro数据集，在测试的时候，都是将图片resize到256测试的是吗？

**Comment by flashszn** [comment]
> 非常抱歉打扰您，我需要再确认下，您在修复任务上，包括：RainDrop数据集，LOL数据集、ISTD数据集和GoPro数据集，在测试的时候，都是将图片resize到256测试的是吗？

具体的，我注意到LOL数据集的图片大小是400*600，那测试的时候需要将测试的GT图片也变成256*256吗？

**Comment by nachifur** [comment]
For image restoration, MATLAB evaluation codes in ./eval.

**Comment by flashszn** [comment]
> For image restoration, MATLAB evaluation codes in ./eval.

> 非常抱歉打扰您，我需要再确认下，您在修复任务上，包括：RainDrop数据集，LOL数据集、ISTD数据集和GoPro数据集，在测试的时候，都是将图片resize到256测试的是吗？
> 
> 具体的，我注意到LOL数据集的图片大小是 400乘600 ，那测试的时候需要将测试的GT图片也变成 256乘256 吗？

非常感谢，我在代码中找到了，和我上述的是一致的
