### ISSUE TITLE
关于图像恢复任务的时间步修改

### ISSUE THREAD

**Issue by yanglibo0512** [nachifur/RDDM#9]
您好，为什么在图像恢复任务中要修改如下代码：
[self.alphas_cumsum[t]*self.num_timesteps, self.betas_cumsum[t]*self.num_timesteps]] -> [t,t]

**Comment by nachifur** [comment]
目前扩散模型一般都是用`[t,t]`，而在本文`[self.alphas_cumsum[t]*self.num_timesteps, self.betas_cumsum[t]*self.num_timesteps]]`仅用来探索Partially Path-independent Generation Process。
